kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - master

steps:

  - name: build
    environment:
      DIVE_SITE_RUSSIA_DEPLOY_PATH:
        from_secret: dive-site-russia-deploy-path
      DIVE_SITE_RUSSIA_FRONTEND_PATH:
        from_secret: dive-site-russia-frontend-path
    commands:
      - cp $${DIVE_SITE_RUSSIA_FRONTEND_PATH}/.env .env
      - docker build --tag dive-site-russia-frontend .

  - name: recreate
    environment:
      DIVE_SITE_RUSSIA_DEPLOY_PATH:
        from_secret: dive-site-russia-deploy-path
    commands:
      - docker-compose -f $${DIVE_SITE_RUSSIA_DEPLOY_PATH}/docker-compose.yml up -d --force-recreate --remove-orphans --no-deps frontend
