kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - master

clone:
  disable: true

steps:

  - name: pull
    environment:
      DIVE_SITE_RUSSIA_FRONTEND_PATH:
        from_secret: dive-site-russia-frontend-path
    commands:
      - cd $${DIVE_SITE_RUSSIA_FRONTEND_PATH} && git pull

  - name: recreate
    environment:
      DIVE_SITE_RUSSIA_DEPLOY_PATH:
        from_secret: dive-site-russia-deploy-path
    commands:
      - docker-compose -f $${DIVE_SITE_RUSSIA_DEPLOY_PATH}/docker-compose.yml up -d --build --no-deps frontend
